<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data_universitas = [
            ['id' => 1, 'nama_universitas' => 'Universitas Syiah Kuala, Banda Aceh'],
            ['id' => 2, 'nama_universitas' => 'Universitas Malikussaleh, Lhokseumawe'],
            ['id' => 3, 'nama_universitas' => 'Politeknik Negeri Lhokseumawe, Lhokseumawe'],
            ['id' => 4, 'nama_universitas' => 'Politeknik Negeri Aceh, Banda Aceh'],
            ['id' => 5, 'nama_universitas' => 'Universitas Samudra, Langsa'],
            ['id' => 6, 'nama_universitas' => 'Universitas Teuku Umar, Meulaboh'],
            ['id' => 7, 'nama_universitas' => 'Politeknik Aceh, Banda Aceh'],
            ['id' => 8, 'nama_universitas' => 'UIN Ar-Raniry, Banda Aceh'],
            ['id' => 9, 'nama_universitas' => 'STAIN Malikussaleh, Lhokseumawe'],
            ['id' => 10, 'nama_universitas' => 'STAIN Zawiyah Cot Kala, Langsa'],
            ['id' => 11, 'nama_universitas' => 'Akademi Komunitas Negeri (AKN) Aceh Barat Daya'],
            ['id' => 12, 'nama_universitas' => 'STAIN Gajah Putih Takengon'],
            ['id' => 13, 'nama_universitas' => 'IAIN Langsa, Langsa'],
            ['id' => 14, 'nama_universitas' => 'STAIN Malikussaleh, Lhokseumawe'],
            ['id' => 15, 'nama_universitas' => 'STAIN Gajah Putih Takengon, Takengon'],
            ['id' => 16, 'nama_universitas' => 'STAIN Teungku Dirundeng, Melabuh'],
            ['id' => 17, 'nama_universitas' => 'Politeknik Kesehatan Banda Aceh'],
            ['id' => 18, 'nama_universitas' => 'Universitas Serambi Mekkah'],
            ['id' => 19, 'nama_universitas' => 'Universitas Sumatera Utara, Medan'],
            ['id' => 20, 'nama_universitas' => 'Universitas Negeri Medan, Medan'],
            ['id' => 21, 'nama_universitas' => 'Politeknik Negeri Medan, Medan'],
            ['id' => 22, 'nama_universitas' => 'Politeknik Negeri Media Kreatif, Medan'],
            ['id' => 23, 'nama_universitas' => 'Institut Agama Islam Negeri Sumatera utara, Medan'],
            ['id' => 24, 'nama_universitas' => 'Poltekes Depkes Medan, Medan'],
            ['id' => 25, 'nama_universitas' => 'STAIN Padang Sidempuan, Padang Sidempuan'],
            ['id' => 26, 'nama_universitas' => 'UIN Sumatera Utara, Medan'],
            ['id' => 27, 'nama_universitas' => 'IAIN Padang Sidempuan, Tapanuli Selatan'],
            ['id' => 28, 'nama_universitas' => 'Akademi Teknik Keselamatan Penerbangan (ATKP) Medan'],
            ['id' => 29, 'nama_universitas' => 'Sekolah Tinggi Agama Kristen Protestan Negeri Tarutung'],
            ['id' => 30, 'nama_universitas' => 'Sekolah Tinggi Penyuluhan Pertanian (STTP) Medan'],
            ['id' => 31, 'nama_universitas' => 'Politeknik Negeri Medan'],
            ['id' => 32, 'nama_universitas' => 'Akademi Tek. Kes. Penerbangan (ATKP), Medan'],
            ['id' => 33, 'nama_universitas' => 'Sekolah Tinggi Penyuluhan Pertanian Medan'],
            ['id' => 34, 'nama_universitas' => 'Universitas Andalas, Padang'],
            ['id' => 35, 'nama_universitas' => 'Universitas Negeri Padang, Padang'],
            ['id' => 36, 'nama_universitas' => 'Politeknik Negeri Padang, Padang'],
            ['id' => 37, 'nama_universitas' => 'Politeknik Pertanian, Payakumbuh'],
            ['id' => 38, 'nama_universitas' => 'STSI (Sekolah Tinggi Seni Indonesia Padang Panjang), Padang Panjang'],
            ['id' => 39, 'nama_universitas' => 'IAIN Imam Bonjol, Padang'],
            ['id' => 40, 'nama_universitas' => 'STAIN Batusangkar'],
            ['id' => 41, 'nama_universitas' => 'STAIN Bukittinggi'],
            ['id' => 42, 'nama_universitas' => 'ISI Padang Panjang'],
            ['id' => 43, 'nama_universitas' => 'IAIN Imam Bonjol, Padang'],
            ['id' => 44, 'nama_universitas' => 'STAIN Sjech M. Djamil Djambek , Bukittinggi'],
            ['id' => 45, 'nama_universitas' => 'Politeknik Negeri Sriwijaya'],
            ['id' => 46, 'nama_universitas' => 'Universitas Riau, Pekanbaru'],
            ['id' => 47, 'nama_universitas' => 'UIN Sultan Syarif Kasim (SUSKA), Pekanbaru'],
            ['id' => 48, 'nama_universitas' => 'Politeknik Negeri Bengkalis'],
            ['id' => 49, 'nama_universitas' => 'Universitas Maritim Raja Ali Haji'],
            ['id' => 50, 'nama_universitas' => 'Politeknik Negeri Batam'],
            ['id' => 51, 'nama_universitas' => 'UIN Sultan Syarif Kasim, Riau'],
            ['id' => 52, 'nama_universitas' => 'STAIN Bengkalis, Riau (Riau)'],
            ['id' => 53, 'nama_universitas' => 'Universitas Jambi, Jambi'],
            ['id' => 54, 'nama_universitas' => 'STAIN Kerinci'],
            ['id' => 55, 'nama_universitas' => 'IAIN Sultan Thaha Saifuddin'],
            ['id' => 56, 'nama_universitas' => 'Politeknik Kesehatan Jambi'],
            ['id' => 57, 'nama_universitas' => 'Universitas Bengkulu, Bengkulu'],
            ['id' => 58, 'nama_universitas' => 'IAIN Bengkulu'],
            ['id' => 59, 'nama_universitas' => 'STAIN CURUP'],
            ['id' => 60, 'nama_universitas' => 'Poltekkes Kemenkes Bengkulu'],
            ['id' => 61, 'nama_universitas' => 'STAIN Curup, Rejang Lebong'],
            ['id' => 62, 'nama_universitas' => 'Universitas Sriwijaya, Palembang'],
            ['id' => 63, 'nama_universitas' => 'Politeknik Negeri Sriwijaya, Palembang'],
            ['id' => 64, 'nama_universitas' => 'Poltekkes depkes Palembang, Palembang'],
            ['id' => 65, 'nama_universitas' => 'Akademi Komunitas Negeri Prabumulih, Prabumulih'],
            ['id' => 66, 'nama_universitas' => 'IAIN Raden Fatah'],
            ['id' => 67, 'nama_universitas' => 'Universitas Lampung, Bandar Lampung'],
            ['id' => 68, 'nama_universitas' => 'Politeknik Negeri Lampung, Bandar Lampung'],
            ['id' => 69, 'nama_universitas' => 'Poltekkes Kemenkes Tanjungkarang, Bandar Lampung'],
            ['id' => 70, 'nama_universitas' => 'STIM (Sekolah Tinggi Olahraga Metro), Kota Metro'],
            ['id' => 71, 'nama_universitas' => 'Institut Agama Islam Negeri Raden Intan, Bandar Lampung'],
            ['id' => 72, 'nama_universitas' => 'STAIN Jurai Siwo Metro'],
            ['id' => 73, 'nama_universitas' => 'IAIN Raden Intan, Bandar Lampung'],
            ['id' => 74, 'nama_universitas' => 'Universitas Bangka Belitung, Bangka Belitung'],
            ['id' => 75, 'nama_universitas' => 'Politeknik Manufaktur, Bangka Belitung'],
            ['id' => 76, 'nama_universitas' => 'Poltekkes Kemenkes Pangkal Pinang, Bangka Belitung'],
            ['id' => 77, 'nama_universitas' => 'STAIN Syekh Abdurrahman Siddik, Bangka Belitung'],
            ['id' => 78, 'nama_universitas' => 'Universitas Sultan Ageng Tirtayasa, Serang'],
            ['id' => 79, 'nama_universitas' => 'Perguruan Tinggi Buddhi, Karawaci'],
            ['id' => 80, 'nama_universitas' => 'IAIN Sultan Maulana Hasanuddin'],
            ['id' => 81, 'nama_universitas' => 'Universitas Pendidikan Indonesia, Kampus Daerah Serang'],
            ['id' => 82, 'nama_universitas' => 'Universitas Terbuka Pondok Cabe'],
            ['id' => 83, 'nama_universitas' => 'Sekolah Tinggi Agama Buddha Negeri Sriwijaya Tangerang'],
            ['id' => 84, 'nama_universitas' => 'Akademi Meteorologi dan Geofisika (AMG) Tangerang'],
            ['id' => 85, 'nama_universitas' => 'Institut Agama Islam Banten (IAIB)'],
            ['id' => 86, 'nama_universitas' => 'Universitas Indonesia'],
            ['id' => 87, 'nama_universitas' => 'Universitas Pertahanan Indonesia (UNHAN)'],
            ['id' => 88, 'nama_universitas' => 'Universitas Negeri Jakarta'],
            ['id' => 89, 'nama_universitas' => 'Universitas Terbuka'],
            ['id' => 90, 'nama_universitas' => 'Politeknik Negeri Jakarta'],
            ['id' => 91, 'nama_universitas' => 'Politeknik Negeri Media Kreatif, Jakarta'],
            ['id' => 92, 'nama_universitas' => 'UIN Syarif Hidayatullah Jakarta'],
            ['id' => 93, 'nama_universitas' => 'Sekolah Tinggi Ilmu Pelayaran Jakarta'],
            ['id' => 94, 'nama_universitas' => 'Sekolah Tinggi Manajemen Industri Indonesia'],
            ['id' => 95, 'nama_universitas' => 'Akademi Pimpinan Perusahaan (APP), Jakarta'],
            ['id' => 96, 'nama_universitas' => 'Institut Ilmu Pemerintahan, IIP, Jakarta'],
            ['id' => 97, 'nama_universitas' => 'Sekolah Tinggi Akuntansi Negara, STAN'],
            ['id' => 98, 'nama_universitas' => 'Sekolah Tinggi Hukum Militer, STHM'],
            ['id' => 99, 'nama_universitas' => 'Sekolah Tinggi Ilmu Administrasi, LAN Jakarta'],
            ['id' => 100, 'nama_universitas' => 'Sekolah Tinggi Ilmu Kepolisian (PTIK), Jakarta'],
            ['id' => 101, 'nama_universitas' => 'Sekolah Tinggi Ilmu Pelayaran (STIP), Jakarta'],
            ['id' => 102, 'nama_universitas' => 'Sekolah Tinggi Ilmu Statistik (STIS), Jakarta'],
            ['id' => 103, 'nama_universitas' => 'Sekolah Tinggi Manajemen Industri(STMI), Jakarta'],
            ['id' => 104, 'nama_universitas' => 'Sekolah Tinggi Penerbangan Indonesia (PI), Jakarta'],
            ['id' => 105, 'nama_universitas' => 'Sekolah Tinggi Perikanan (STP), Jakarta'],
            ['id' => 106, 'nama_universitas' => 'Politeknik Kesehatan Jakarta I'],
            ['id' => 107, 'nama_universitas' => 'Politeknik Kesehatan Jakarta II'],
            ['id' => 108, 'nama_universitas' => 'Politeknik Negeri Jakarta'],
            ['id' => 109, 'nama_universitas' => 'Politeknik Manufaktur Negeri Bandung, Bandung'],
            ['id' => 110, 'nama_universitas' => 'Universitas Pendidikan Indonesia, Bandung'],
            ['id' => 111, 'nama_universitas' => 'Universitas Padjadjaran, Bandung'],
            ['id' => 112, 'nama_universitas' => 'Universitas Jenderal Achmad Yani, Bandung'],
            ['id' => 113, 'nama _universitas' => 'Institut Pertanian Bogor, Bogor'],
            ['id' => 114, 'nama_universitas' => 'Institut Teknologi Bandung, Bandung'],
            ['id' => 115, 'nama_universitas' => 'Politeknik Negeri Bandung, Bandung'],
            ['id' => 116, 'nama_universitas' => 'Politeknik Indramayu, Indramayu'],
            ['id' => 117, 'nama_universitas' => 'Universitas Siliwangi (UNSIL), Tasikmalaya'],
            ['id' => 118, 'nama_universitas' => 'Universitas Singaperbangsa (UNSIKA), Kampus Daerah Karawang'],
            ['id' => 119, 'nama_universitas' => 'Universitas Swadaya Gunung Jati (Unswagati) di Kota Cirebon'],
            ['id' => 120, 'nama_universitas' => 'Universitas Pendidikan Indonesia, Kampus Daerah Cibiru'],
            ['id' => 121, 'nama_universitas' => 'Universitas Pendidikan Indonesia, Kampus Daerah Tasikmalaya'],
            ['id' => 122, 'nama_universitas' => 'Universitas Pendidikan Indonesia, Kampus Daerah Sumedang'],
            ['id' => 123, 'nama_universitas' => 'Universitas Pendidikan Indonesia, Kampus Daerah Purwakarta'],
            ['id' => 124, 'nama_universitas' => 'Akademi Ilmu Pemasyarakatan (AKIP), Depok'],
            ['id' => 125, 'nama_universitas' => 'Akademi Imigrasi (AIM) Depok'],
            ['id' => 126, 'nama_universitas' => 'Akademi Kimia Analis (AKA) Bogor'],
            ['id' => 127, 'nama_universitas' => 'Sekolah Tinggi Ilmu Administrasi, Bandung'],
            ['id' => 128, 'nama_universitas' => 'Sekolah Tinggi Sandi Negara (STSN), Bogor'],
            ['id' => 129, 'nama_universitas' => 'Sekolah Tinggi Seni Indonesia (STSI), Bandung'],
            ['id' => 130, 'nama_universitas' => 'Sekolah Tinggi Transportasi Darat (STTD), Bekasi'],
            ['id' => 131, 'nama_universitas' => 'Sekolah Tinggi Kesejahteraan Sosial (STKS), Bandung'],
            ['id' => 132, 'nama_universitas' => 'Sekolah Tinggi Pemerintahan Dalam Negeri (STPDN), Sumedang'],
            ['id' => 133, 'nama_universitas' => 'Sekolah Tinggi Penyuluhan Pertanian (STTP) Bogor'],
            ['id' => 134, 'nama_universitas' => 'STAIN Cirebon'],
            ['id' => 135, 'nama_universitas' => 'Politeknik Kesehatan Bandung'],
            ['id' => 136, 'nama_universitas' => 'Politeknik Manufaktur Bandung'],
            ['id' => 137, 'nama_universitas' => 'Politeknik Negeri Bali, Badung'],
            ['id' => 138, 'nama_universitas' => 'Universitas Diponegoro, Semarang'],
            ['id' => 139, 'nama_universitas' => 'Universitas Negeri Semarang, Semarang'],
            ['id' => 140, 'nama_universitas' => 'Universitas Jenderal Soedirman, Purwokerto'],
            ['id' => 141, 'nama_universitas' => 'Universitas Negeri Surakarta Sebelas Maret, Surakarta'],
            ['id' => 142, 'nama_universitas' => 'Politeknik Negeri Semarang, Semarang'],
            ['id' => 143, 'nama_universitas' => 'Politeknik Maritim Negeri Indonesia, Semarang'],
            ['id' => 144, 'nama_universitas' => 'Institut Seni Indonesia Surakarta, Surakarta (ISI Solo, dahulu STSI)'],
            ['id' => 145, 'nama_universitas' => 'Universitas Tidar Magelang, Magelang'],
            ['id' => 146, 'nama_universitas ' => 'UIN Walisongo, Semarang'],
            ['id' => 147, 'nama_universitas' => 'IAIN Surakarta, Surakarta'],
            ['id' => 148, 'nama_universitas' => 'STAIN Kudus, Kudus'],
            ['id' => 149, 'nama_universitas' => 'STAIN Pekalongan, Pekalongan'],
            ['id' => 150, 'nama_universitas' => 'IAIN Salatiga, Salatiga'],
            ['id' => 151, 'nama_universitas' => 'IAIN Purwokerto, Purwokerto'],
            ['id' => 152, 'nama_universitas' => 'Akademi Kepolisian (AKPOL),Semarang'],
            ['id' => 153, 'nama_universitas' => 'Akademi Militer (AKMIL) TNI AD, Magelang'],
            ['id' => 154, 'nama_universitas' => 'Akademi Minyak dan Gas Bumi (AKAMIGAS), Blora'],
            ['id' => 155, 'nama_universitas' => 'Akademi Sanitasi dan Kesehatan Lingkungan (ASKK), Purwokerto'],
            ['id' => 156, 'nama_universitas' => 'Sekolah Tinggi Seni Indonesia (STSI), Surakarta'],
            ['id' => 157, 'nama_universitas' => 'Sekolah Tinggi Penyuluhan Pertanian (STTP) Magelang'],
            ['id' => 158, 'nama_universitas' => 'Politeknik Ilmu Pelayaran Semarang'],
            ['id' => 159, 'nama_universitas' => 'Politeknik Kesehatan Semarang'],
            ['id' => 160, 'nama_universitas' => 'Politeknik Kesehatan Surakarta'],
            ['id' => 161, 'nama_universitas' => 'Universitas Gadjah Mada'],
            ['id' => 162, 'nama_universitas' => 'Universitas Negeri Yogyakarta'],
            ['id' => 163, 'nama_universitas' => 'Institut Seni Indonesia Yogyakarta'],
            ['id' => 164, 'nama_universitas' => 'Universita Terbuka  UPBJJ Yogyakarta'],
            ['id' => 165, 'nama_universitas' => 'Akademi Teknologi Kulit Yogyakarta (ATK)'],
            ['id' => 166, 'nama_universitas' => 'Universitas Pembangunan Nasional Veteran (UPN), Yogyakarta'],
            ['id' => 167, 'nama_universitas' => 'UIN Sunan Kalijaga'],
            ['id' => 168, 'nama_universitas' => 'Akademi Angkatan Udara (AAU), Yogyakarta'],
            ['id' => 169, 'nama_universitas' => 'Sekolah Tinggi Pertanahan Nasional (STPN), Yogyakarta'],
            ['id' => 170, 'nama_universitas' => 'Sekolah Tinggi Teknologi Nuklir (STTN), Yogyakarta'],
            ['id' => 171, 'nama_universitas' => 'Politeknik Kesehatan Yogyakarta'],
            ['id' => 172, 'nama_universitas' => 'Universitas Airlangga, Surabaya'],
            ['id' => 173, 'nama_universitas' => 'Universitas Negeri Surabaya, Surabaya'],
            ['id' => 174, 'nama_universitas' => 'Universitas Brawijaya, Malang'],
            ['id' => 175, 'nama_universitas' => 'Universitas Negeri Malang, Malang'],
            ['id' => 176, 'nama_universitas' => 'Universitas Jember, Jember'],
            ['id' => 177, 'nama_universitas' => 'Universitas Trunojoyo, Bangkalan'],
            ['id' => 178, 'nama_universitas' => 'Politeknik Elektronika Negeri Surabaya, Surabaya'],
            ['id' => 179, 'nama_universitas' => 'Politeknik Perkapalan Negeri Surabaya, Surabaya'],
            ['id' => 180, 'nama_universitas' => 'Politeknik Negeri Madura, Sampang'],
            ['id' => 181, 'nama_universitas' => 'Politeknik Negeri Malang, Malang'],
            ['id' => 182, 'nama_universitas' => 'Politeknik Negeri Madiun, Madiun'],
            ['id' => 183, 'nama_universitas' => 'Politeknik Negeri Jember, Jember'],
            ['id' => 184, 'nama_universitas' => 'Institut Teknologi Sepuluh Nopember, Surabaya'],
            ['id' => 185, 'nama_universitas' => 'Akademi Komunitas Negeri, Bojonegoro'],
            ['id' => 186, 'nama_universitas' => 'Akademi Komunitas Negeri, Pacitan'],
            ['id' => 187, 'nama_universitas' => 'Universitas Pembangunan Nasional Veteran (UPN), Surabaya'],
            ['id' => 188, 'nama_universitas' => 'Politeknik Negeri Banyuwangi, Banyuwangi'],
            ['id' => 189, 'nama_universitas' => 'Akademi Komunitas Negeri Lamongan, Lamongan'],
            ['id' => 190, 'nama_universitas' => 'Akademi Komunitas Negeri Sumenep. Sumenep'],
            ['id' => 191, 'nama_universitas' => 'Akademi Komunitas Negeri Bojonegoro, Bojonegoro'],
            ['id' => 192, 'nama_universitas' => 'Universitas Islam Negeri Maulana Malik Ibrahim, Malang'],
            ['id' => 193, 'nama_universitas' => 'STAIN Kediri'],
            ['id' => 194, 'nama_universitas' => 'STAIN Ponorogo'],
            ['id' => 195, 'nama_universitas' => 'UIN Sunan Ampel'],
            ['id' => 196, 'nama_universitas' => 'IAIN Tulungagung'],
            ['id' => 197, 'nama_universitas' => 'UIN Maulana Malik Ibrahim, Malang'],
            ['id' => 198, 'nama_universitas' => 'STAIN Pamekasan, Pamekasan'],
            ['id' => 199, 'nama_universitas' => 'Akademi Angkatan Laut (AAL), Surabaya'],
            ['id' => 200, 'nama_universitas' => 'Teknik Keselamatan Penerbangan (ATKP) Surabaya'],
            ['id' => 201, 'nama_universitas' => 'Sekolah Tinggi Penyuluhan Pertanian (STTP) Malang'],
            ['id' => 202, 'nama_universitas' => 'IAIN Jember, Jember'],
            ['id' => 203, 'nama_universitas' => 'Politeknik Elektronika Negeri Surabaya'],
            ['id' => 204, 'nama_universitas' => 'Politeknik Kesehatan Malang'],
            ['id' => 205, 'nama_universitas' => 'Politeknik Kesehatan Surabaya'],
            ['id' => 206, 'nama_universitas' => 'Politeknik Pertanian Negeri Jember'],
            ['id' => 207, 'nama_universitas' => 'Akademi TKP â€“ Surabaya'],
            ['id' => 208, 'nama_universitas' => 'Universitas Mataram, Mataram'],
            ['id' => 209, 'nama_universitas' => 'IAIN Mataram, Lombok'],
            ['id' => 210, 'nama_universitas' => 'Sekolah Tinggi Agama Hindu Negeri (STAHN) Gde Puja, Mataram'],
            ['id' => 211, 'nama_universitas' => 'Universitas Nusa Cendana, Kupang'],
            ['id' => 212, 'nama_universitas' => 'Politeknik Negeri Kupang, Kupang'],
            ['id' => 213, 'nama_universitas' => 'Politeknik Pertanian Negeri Kupang, Kupang'],
            ['id' => 214, 'nama_universitas' => 'Universitas Udayana, Denpasar'],
            ['id' => 215, 'nama_universitas' => 'Universitas Pendidikan Ganesha, Singaraja'],
            ['id' =>  216, 'nama_universitas' => 'Politeknik Negeri Bali, Kuta-Badung'],
            ['id' => 217, 'nama_universitas' => 'Institut Seni Indonesia Denpasar, Denpasar'],
            ['id' => 218, 'nama_universitas' => 'Politeknik Negeri Tanah Lot'],
            ['id' => 219, 'nama_universitas' => 'Institut Hindu Dharma Negeri (IHDN) Denpasar'],
            ['id' => 220, 'nama_universitas' => 'Akademi Kebidanan Pemprov Bali singaraja'],
            ['id' => 221, 'nama_universitas' => 'Sekolah Tinggi Pariwisata Bali'],
            ['id' => 222, 'nama_universitas' => 'Sekolah Tinggi Agama Kristen Negeri (STAKN) Denpasar'],
            ['id' => 223, 'nama_universitas' => 'Politeknik Kesehatan Denpasar'],
            ['id' => 224, 'nama_universitas' => 'Universitas Tanjungpura, Pontianak'],
            ['id' => 225, 'nama_universitas' => 'Politeknik Negeri Pontianak, Pontianak'],
            ['id' => 226, 'nama_universitas' => 'Politeknik Kesehatan Kementerian Kesehatan, Pontianak'],
            ['id' => 227, 'nama_universitas' => 'Politeknik Terpikat Sambas'],
            ['id' => 228, 'nama_universitas' => 'Politeknik Tonggak Equator'],
            ['id' => 229, 'nama_universitas' => 'Politeknik Ketapang'],
            ['id' => 230, 'nama_universitas' => 'Politeknik Tunas Bangsa'],
            ['id' => 231, 'nama_universitas' => 'IAIN Pontianak sebelumnya STAIN Pontianak'],
            ['id' => 232, 'nama_universitas' => 'Universitas Palangka Raya, Palangka Raya'],
            ['id' => 233, 'nama_universitas' => 'IAIN Palangkaraya, Palangkaraya'],
            ['id' => 234, 'nama_universitas' => 'Sekolah Tinggi Agama Hindu Negeri Tampung Peyang, Palangka Raya'],
            ['id' => 235, 'nama_universitas' => 'Sekolah Tinggi Agama Kristen Negeri (STAKN) Palangkaraya'],
            ['id' => 236, 'nama_universitas' => 'Universitas Lambung Mangkurat, Banjarmasin'],
            ['id' => 237, 'nama_universitas' => 'Politeknik Negeri Banjarmasin, Banjarmasin'],
            ['id' => 238, 'nama_universitas' => 'IAIN ANTASARI, Banjarmasin'],
            ['id' => 239, 'nama_universitas' => 'Poltekkes Banjarmasin'],
            ['id' => 240, 'nama_universitas' => 'Politeknik Pertanian Negeri Samarinda'],
            ['id' => 241, 'nama_universitas' => 'Universitas Mulawarman, Samarinda'],
            ['id' => 242, 'nama_universitas' => 'Politeknik Negeri Samarinda, Samarinda'],
            ['id' => 243, 'nama_universitas' => 'Politeknik Pertanian Negeri Samarinda, Samarinda'],
            ['id' => 244, 'nama_universitas' => 'Universitas Borneo Tarakan, Tarakan'],
            ['id' => 245, 'nama_universitas' => 'Politeknik Balikpapan, Balikpapan'],
            ['id' => 246, 'nama_universitas' => 'IAIN Samarinda, Samarinda'],
            ['id' => 247, 'nama_universitas' => 'Universitas Borneo Tarakan'],
            ['id' => 248, 'nama_universitas' => 'Universitas Sam Ratulangi, Manado'],
            ['id' => 249, 'nama_universitas' => 'Universitas Negeri Manado, Manado'],
            ['id' => 250, 'nama_universitas' => 'Politeknik Negeri Manado, Manado'],
            ['id' => 251, 'nama _universitas' => 'Politeknik Negeri Nusa Utara, Tahuna'],
            ['id' => 252, 'nama_universitas' => 'IAIN Manado, Manado (Sulawesi Utara)'],
            ['id' => 253, 'nama_universitas' => 'Politeknik Kesehatan Manado'],
            ['id' => 254, 'nama_universitas' => 'Politeknik Negeri Manado'],
            ['id' => 255, 'nama_universitas' => 'Universitas Negeri Gorontalo, Gorontalo'],
            ['id' => 256, 'nama_universitas' => 'IAIN Sultan Amai, Gorontalo'],
            ['id' => 257, 'nama_universitas' => 'Universitas Tadulako, Palu'],
            ['id' => 258, 'nama_universitas' => 'Sekolah Tinggi Ilmu Ekonomi (YPP Mujahidin), Tolitoli'],
            ['id' => 259, 'nama_universitas' => 'IAIN Dato Karamau, Palu'],
            ['id' => 260, 'nama_universitas' => 'STAIN Datokarama, Palu'],
            ['id' => 261, 'nama_universitas' => 'Politeknik Kesehatan Kemenkes Makassar, Makassar'],
            ['id' => 262, 'nama_universitas' => 'Universitas Hasanuddin, Makassar'],
            ['id' => 263, 'nama_universitas' => 'Universitas Negeri Makassar'],
            ['id' => 264, 'nama_universitas' => 'Politeknik Pertanian Negeri Pangkajene Kepulauan, Pangkajene Kepulauan'],
            ['id' => 265, 'nama_universitas' => 'Politeknik Negeri Ujung pandang, Makassar'],
            ['id' => 266, 'nama_universitas' => 'Universitas Maiwa Enrekang'],
            ['id' => 267, 'nama_universitas' => 'Politeknik Negeri Media Kreatif, Makassar'],
            ['id' => 268, 'nama_universitas' => 'Universitas Islam Negeri Makassar'],
            ['id' => 269, 'nama_universitas' => 'UIN Alauddin, Makassar'],
            ['id' => 270, 'nama_universitas' => 'STAIN Watampone, Bone'],
            ['id' => 271, 'nama_universitas' => 'STAIN Parepare, Parepare'],
            ['id' => 272, 'nama_universitas' => 'IAIN Palopo, Palopo'],
            ['id' => 273, 'nama_universitas' => 'Akademi Teknik Keselamatan Penerbangan (ATKP) Makasar'],
            ['id' => 274, 'nama_universitas' => 'Sekolah Tinggi Ilmu Adm, Ujung Pandang'],
            ['id' => 275, 'nama_universitas' => 'Sekolah Tinggi Seni Indonesia, Padang Panjang'],
            ['id' => 276, 'nama_universitas' => 'Sekolah Tinggi Agama Kristen Negeri (STAKN) Toraja'],
            ['id' => 277, 'nama_universitas' => 'Sekolah Tinggi Penyuluhan Pertanian (STTP) Gowa'],
            ['id' => 278, 'nama_universitas' => 'Akademi Teknik Keselamatan Penerbangan Makasar'],
            ['id' => 279, 'nama_universitas' => 'Universitas Haluoleo, Kendari'],
            ['id' => 280, 'nama_universitas' => 'Sekolah Tinggi Pertanian (STIP) Muna Kampus Baru, Muna'],
            ['id' => 281, 'nama_universitas' => 'STAIN Kendari'],
            ['id' => 282, 'nama_universitas' => 'Universitas 19 November Kolaka'],
            ['id' => 283, 'nama_universitas' => 'Universitas Muhammadiyah Kendari'],
            ['id' => 284, 'nama_universitas' => 'Universitas Lakidende'],
            ['id' => 285, 'nama_universitas' => 'Universitas Dayanu Iksanudin'],
            ['id' => 286, 'nama_universitas' => 'Universitas Muhammadiyah But on'],
            ['id' => 287, 'nama_universitas' => 'Universitas Sulawesi Tenggara'],
            ['id' => 288, 'nama_universitas' => 'IAIN Kendari, Palu'],
            ['id' => 289, 'nama_universitas' => 'Universitas Negeri Sulawesi Barat'],
            ['id' => 290, 'nama_universitas' => 'Universitas Pattimura, Ambon'],
            ['id' => 291, 'nama_universitas' => 'Universitas Darussalam, Ambon'],
            ['id' => 292, 'nama_universitas' => 'Politeknik Negeri Ambon, Ambon'],
            ['id' => 293, 'nama_universitas' => 'Politeknik Perikanan Negeri Tual, Tual'],
            ['id' => 294, 'nama_universitas' => 'STAKPN Ambon'],
            ['id' => 295, 'nama_universitas' => 'IAIN Ambon'],
            ['id' => 296, 'nama_universitas' => 'Sekolah Tinggi Agama Kristen Protestan Negeri Ambon'],
            ['id' => 297, 'nama_universitas' => 'STAIN Ambon'],
            ['id' => 298, 'nama_universitas' => 'Universitas Khairun, Ternate'],
            ['id' => 299, 'nama_universitas' => 'IAIN Ternate, Ternate'],
            ['id' => 300, 'nama_universitas' => 'Universitas Cendrawasih, Jayapura'],
            ['id' => 301, 'nama_universitas' => 'Universitas Musamus Merauke, Merauke'],
            ['id' => 302, 'nama_universitas' => 'STAIN Al-Fatah, Jayapura'],
            ['id' => 303, 'nama_universitas' => 'Sekolah Tinggi. Agama Kristen Negeri (STAKN) Jayapura'],
            ['id' => 304, 'nama_universitas' => 'Universitas Negeri Papua, Manokwari'],
            ['id' => 305, 'nama_universitas' => 'STAIN Sorong, Sorong'],
            ['id' => 306, 'nama_universitas' => 'Sekolah Tinggi Penyuluhan Pertanian (STTP) Manokwari']
        ];

        DB::table('data_universitas')->insert($data_universitas);
    }
}
